name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t hello-app .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u "${{ secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Tag Docker Image
        run: docker tag hello-app joe2727/hello-app:latest

      - name: Push Docker Image to Docker Hub
        run: docker push joe2727/hello-app:latest